services:
  - type: web
    name: telegram-quotes-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_KEY
        sync: false